---
  - name: copy create_itrust
    copy:
        src: create_itrust.yml
        dest: /home/ubuntu/create_itrust.yml
  - name: copy variables.yml file
    copy:
        src: variables.yml
        dest: /home/ubuntu/variables.yml
  - name: copy pem file
    copy:
        src: "/vagrant/{{ pem_file_name }}"
        dest: "/home/ubuntu/{{ pem_file_name }}"
  - name: change permission of mile3.pem file
    file: 
          path: "/home/ubuntu/{{ pem_file_name }}"
          mode: 0400
  - name: copy hosts
    copy:
        src: hosts
        dest: /home/ubuntu/hosts
  - name: copy create_kube
    copy:
        src: create_kube.yml
        dest: /home/ubuntu/create_kube.yml
  - name: copy create_checkbox
    copy:
        src: create_checkbox.yml
        dest: /home/ubuntu/create_checkbox.yml
  # - name: copy DevOps.pem file
  #   copy:
  #       src: "/vagrant/{{ pem_file_name }}"
  #       dest: "/home/ubuntu/{{ pem_file_name }}"
  # - name: change permission of DevOps.pem file
  #   file: 
  #         path: "/home/ubuntu/{{ pem_file_name }}"
  #         mode: 0400
  - name: create .aws folder
    file:
       path: /home/ubuntu/.aws
       state: directory

    #command: mkdir .aws
  - name: copy credentials template
    copy:   
       src: credentials
       dest: /home/ubuntu/.aws/credentials
  - name: copy foo.conf template file
    copy:
        src: foo.conf
        dest: "/home/ubuntu/foo.conf"
  - name: copy crdential_copy.yml template file
    copy:
        src: credential_copy.yml
        dest: "/home/ubuntu/credential_copy.yml"
  - name: copy checkbox_main.yml template file
    copy:
        src: checkbox_main.yml
        dest: "/home/ubuntu/checkbox_main.yml"
  - name: copy itrust_main.yml template file
    copy:
        src: itrust_main.yml
        dest: "/home/ubuntu/itrust_main.yml"
  - name: copy ansible.cfg template file
    copy:
        src: ansible.cfg
        dest: "/home/ubuntu/ansible.cfg"

  
