---

  - name: add grafana apt repository
    become: true
    apt_repository:
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present
      update_cache: yes

  - name: add grafana apt-key
    become: true
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Update APT package manager repositories cache
    become: true
    apt:
      update_cache: yes

  - name: Upgrade installed packages
    become: true
    apt:
      upgrade: dist

  - name: install grafana
    become: true
    apt:
      name: grafana
      state: present
      update_cache: yes

  - name: install package to fetch over https
    become: true
    apt:
      name: apt-transport-https
      state: present
      update_cache: yes
	  
  - name: Start service grafana
    service:
      name: grafana-server
      state: started

  - name: Configure the Grafana server to start at boot time
    become: true
    command: update-rc.d grafana-server defaults

  - name: restart service grafana
    service:
      name: grafana-server
      state: restarted
      
  - name: configure cloudwatch as data source
    copy:
        src: cloudwatch.yml
        dest: /etc/grafana/provisioning/datasources
  
  - name: Integrate cloudwatch and grafana
    copy:   
        src: credentials
        dest: /usr/share/grafana/.credentials
        mode: 0644
        
