---
- hosts: ec2hosts
  remote_user: ubuntu
  vars:
        ansible_ssh_private_key_file: /vagrant/mile3.pem
        ansible_python_interpreter: /usr/bin/python3
  connection: ssh
  roles:
    - ansibleins

