---
  - name: install ansible
    become: yes
    apt :
       name: "{{ packages }}"
    vars:
       packages: 
         
         - python-pip
         - python3-pip
  - name: update apt
    become: true
    apt:
       update_cache: yes
  - name: install ansi
    apt: 
       name:  software-properties-common
  - name: add repo
    become: yes
    command: apt-add-repository --yes --update ppa:ansible/ansible
  - name: ansible ins
    become: yes
    apt:
       name: ansible
  - name: insatll boto
    become: yes
    command: pip install boto
  - name: insatll boto3
    become: yes
    command: pip install boto3
   
         
       
