---
  - name: checking if folder exists
<<<<<<< HEAD
    stat: path=/home/vagrant/jobs/checkBox.yml
    register: st

  - name: checking if folder exists
    stat: path=/home/vagrant/jobs/ITrust.yml
=======
    stat: path=/home/ubuntu/jobs/checkBox.yml
    register: st

  - name: checking if folder exists
    stat: path=/home/ubuntu/jobs/ITrust.yml
>>>>>>> integrated
    register: sta

  - name: copy the jobs file to the jobs folder
    become: yes
    copy:
      src: jobs/
<<<<<<< HEAD
      dest: /home/vagrant/jobs/
=======
      dest: /home/ubuntu/jobs/
>>>>>>> integrated
      mode: 0777
  - name: Update jenkins job
    command: .local/bin/jenkins-jobs --conf jobs/jenkins_jobs.ini --user jenkins --password "{{jenkins_password}}" update jobs/
    args:
<<<<<<< HEAD
      chdir: /home/vagrant
=======
      chdir: /home/ubuntu
>>>>>>> integrated

  - name: change port
    become: true
    lineinfile:
      path: /etc/default/jenkins
      regexp: '^HTTP_PORT='
      line: 'HTTP_PORT=8081'

  - name: restart jenkins service, in all cases
    become: yes
    systemd:
      name: jenkins
      state: restarted

  - name: Wait for jenkins to come up
    uri:
       url: "http:/{{CURL}}login?from=%2F"
       status_code: 200
    register: result
    until: result.status == 200
    retries: 20
    delay: 5


