---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    become: true
    become_user: ubuntu
    gather_facts: False
    tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      instance_type: t2.micro
      security_group: ansible # Change the security group name here
      image:  ami-0565af6e282977273 #ami-08692d171e3cf02d6 #ami-005bdb005fb00e791 # This is an AMI i created myself
      keypair: devops2 # This is one of my keys that i already have in AWS
      region: us-east-1 # Change the Region
      count: 1

    # Task that will be used to Launch/Create an EC2 Instance
    tasks:

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for webserver Servers
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8081
              to_port: 8081
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall

      - name: Launch the new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2

      - debug:
           msg: "{{ ec2.instances }}"

    #  - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
    #    local_action: lineinfile 
    #                  dest="./hosts" 
    #                  regexp= '^(.*)CURL(.*)$' 
    #                  line=  {{ item.public_ip }}" 

    #    with_items: "{{ ec2.instances }}"
      - name: Add all instance public IPs to host group
        add_host: hostname={{ item.public_ip }} groups=checkbox
        with_items: "{{ ec2.instances }}"
      # - name: replace line
      #   lineinfile:
      #           dest: /vagrant/variables.yml 
      #           regexp: '^(.*)CURL: (.*)$' 
      #           line: 'CURL: "{{ ec2.instances.public_ip }}:8081/" '
      #           backrefs: yes

      - name: Wait for SSH to come up
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: "{{ ec2.instances }}"

      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: checkbox
  # - name: clone itrust
  #   sudo: no
  #   hosts: ec2hosts
  #   remote_user: ubuntu
  #   vars:
  #       ansible_ssh_private_key_file: /vagrant/mile3.pem
  #       ansible_python_interpreter: /usr/bin/python3
  #   connection: ssh
  #   tasks:
  #     - name: git clone itrust
  #       #`sudo: yes
  #       #hosts: webserver
  #       git: repo=https://github.com/gautamworah96/iTrust dest=/home/ubuntu/iTrust2-v4
  #       ignore_errors: yes
