---
- name: copy credential file
  remote_user: ubuntu
  hosts: kube
  vars:
        ansible_ssh_private_key_file: "/home/ubuntu/devops2.pem"
        ansible_python_interpreter: /usr/bin/python3
  connection: ssh

  gather_facts: False

  tasks:
    - name: create .aws folder
      file:
        path: /home/ubuntu/.aws
        state: directory
    - name: copy credential
      copy:
        src: /home/ubuntu/.aws/credentials
        dest: /home/ubuntu/.aws/credentials
