---
    
    - name: git clone iTrust
      git: 
        repo: "{{itrust_repo}}"
        dest: /home/ubuntu/iTrust2-v4
      ignore_errors: yes

    - name: copy db.properties
      template:       
         src: /vagrant/roles/itrust/template/db.properties.template
         dest: /home/ubuntu/iTrust2-v4/iTrust2/src/main/java/db.properties

    - name: copy email.properties
      template:
         src: /vagrant/roles/itrust/template/email.properties.template
         dest: /home/ubuntu/iTrust2-v4/iTrust2/src/main/java/email.properties
 

    - name: Add remote url for itrust
      template:
        src: config-itrust
        remote_src: no
        dest: /home/ubuntu/iTrust2-v4/.git/config
        owner: ubuntu
        group: ubuntu
        mode: 0664
 
    - name: copy the post-receive hook remote repository itrust
      become: yes
      template:
        src: post-receive-iTrust
        dest: /home/ubuntu/deploy/jenkins-itrust.git/hooks/post-receive
        owner: root
        group: root
        mode: 0777
